"use strict";
let num = 12;
let str = "Hello";
let bool = true;
let n = null;
let und = undefined;
let arr = [1, 2, 3];
console.log(num, str, bool, n, und, arr);
let num1 = 125;
let str1 = "Hello World";
let bool1 = false;
let n1 = null;
let und1 = undefined;
let arr1 = [1, 2, 3, 4, 5, 6];
console.log(num1, str1, bool1, n1, und1, arr1);
let elements = [...arr, ...arr1];
elements.push(9);
console.log(elements);
elements.shift();
console.log(elements);
console.log(elements.length);
elements.sort();
console.log(elements);
